### ISSUE TITLE
error in poll(): Invalid argument

### ISSUE THREAD

**Issue by frankvandenhurk** [SIDN/spin#89] opened 2022-01-18 19:37 UTC
After having spind with external source (spin-pcap-reader) run for a while (with a high traffic interface it triggers faster) i get a high volume constant stream of the same error on stout:

error in poll(): Invalid argument

Within 24 hours I had a 70 GB logfile. Any clue what's going on? Is there anything I can test of capture to help you rind the cause?

**Comment by cschutijser** [comment] 2022-01-19 16:04
Thanks for your report again. I have an idea what could cause this but no patch to test yet. I hope I have time tomorrow to work on it.

**Comment by cschutijser** [comment] 2022-01-25 15:08
Thanks for your patience. I think that should be fixed with commit 8534d41bc7e1d4122abe307c7549502b087d090b. Can you check and see if the problem is indeed solved on your end?

**Comment by frankvandenhurk** [comment] 2022-01-27 18:57
I tried to reproduce the error but wasn't able to do so.

**Comment by cschutijser** [comment] 2022-02-03 08:16
Great to hear, thanks!

**Closed by cschutijser** 2022-02-03 08:16 UTC
